name: adsdb

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address=":9001"
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${SECRET_ACCESS_KEY}
    volumes:
      - minio-data:/data
  chromadb:
    image: ghcr.io/chroma-core/chroma # Official ChromaDB image
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma # Persist ChromaDB data
  # app:
  #   image: ghcr.io/carles-aguilera-pilo/adsdb:latest
  #   command: "pipeline" 
  #   network_mode: "host"
  #   ports:
  #     - "8501:8501"
  #   env_file:
  #     - .env
  #   environment:
  #     ACCESS_KEY_ID: ${ACCESS_KEY_ID}
  #     SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
  #     S3_API_ENDPOINT: ${S3_API_ENDPOINT}
  #     S3_CONSOLE_ENDPOINT: ${S3_CONSOLE_ENDPOINT}
  #     CHROMADB_ENDPOINT: ${CHROMADB_ENDPOINT}
  #     CHROMADB_PORT: ${CHROMADB_PORT}
  #     GEMINI_API_KEY: ${GEMINI_API_KEY}
  #   depends_on:
  #     - minio
  #     - chromadb

volumes:
  chroma-data:
  minio-data:
